spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
